# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e511aab4e8d9a76ed5090b3f61b9f555"
name = "bitcubetask"
handle = "bitcubetask"
application_url = "https://jury-enhance-columbia-too.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ad46e5d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jury-enhance-columbia-too.trycloudflare.com/auth/callback",
  "https://jury-enhance-columbia-too.trycloudflare.com/auth/shopify/callback",
  "https://jury-enhance-columbia-too.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
